<a href="https://colab.research.google.com/github/TohirBahromov/week3_lab/blob/main/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [1]:
import torch

# TODO: Create a scalar tensor
scalar = torch.tensor(42)

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor(42)
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [3]:
# TODO: Create a vector tensor
vector = torch.tensor([1,2,3,4])

# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

tensor([1, 2, 3, 4])
Number of dimensions: 1
Shape: torch.Size([4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [4]:
# TODO: Create a matrix tensor
matrix = torch.tensor([
    [1,2,3],
    [4,5,6]
])

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions: 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [7]:
# TODO: Create a 3D tensor
tensor_3d = torch.arange(1, 9).reshape(2, 2, 2)

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Number of dimensions: 3
Shape: torch.Size([2, 2, 2])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [6]:
# TODO: Create random tensor
random_tensor = torch.rand(4,4)

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.0639, 0.0387, 0.1396, 0.3563],
        [0.4046, 0.2116, 0.9043, 0.0587],
        [0.4156, 0.6298, 0.1453, 0.3163],
        [0.4544, 0.5173, 0.3650, 0.3650]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [8]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(3, 224, 224)

print(f"Shape: {image_tensor.shape}")

Shape: torch.Size([3, 224, 224])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [10]:
# TODO: Create zeros tensor
zeros = torch.zeros(5,5)
print(zeros)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [11]:
random_tensor = torch.rand(3, 3)
# TODO: Create ones like
ones_like = torch.ones(3,3)
print(ones_like)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [12]:
# TODO: Create range tensor
range_tensor = torch.arange(1, 21)
print(range_tensor)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])


## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [13]:
# TODO: float16 tensor
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)

# TODO: int64 tensor
int64_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.int64)

print(float16_tensor, int64_tensor)

tensor([1., 2., 3.], dtype=torch.float16) tensor([1, 2, 3])


### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [15]:
# TODO: Change dtype
float32_tensor = float16_tensor.type(torch.float32)
print(float32_tensor, float32_tensor.dtype)

tensor([1., 2., 3.]) torch.float32


## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [16]:
# TODO: Create tensor and print info
info_tensor = torch.rand(2,3,4)
print(info_tensor.shape, info_tensor.dtype, info_tensor.device)

torch.Size([2, 3, 4]) torch.float32 cpu


## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [17]:
tensor = torch.tensor([10, 20, 30])
# TODO: Add 5
step1 = tensor + 5
# TODO: Subtract 10
step2 = step1 - 10
# TODO: Multiply by 2
step3 = step2 * 2
# TODO: Divide by 10
final_result = step3 / 10
print(f"Final Tensor: {final_result}")

Final Tensor: tensor([1., 3., 5.])


### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [18]:
# TODO: Create A and B
A = torch.rand(2,3)
B = torch.rand(3,2)

# TODO: Matrix mul using torch.mm
result_mm = torch.mm(A,B)

# TODO: Matrix mul using @
result_at = A @ B

print(result_mm)
print(result_at)

tensor([[0.6104, 0.9492],
        [0.6507, 1.3701]])
tensor([[0.6104, 0.9492],
        [0.6507, 1.3701]])


## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [21]:
agg_tensor = torch.arange(0, 101, dtype=torch.float32)

tensor_min  = agg_tensor.min()
tensor_max  = agg_tensor.max()
tensor_mean = agg_tensor.mean()
tensor_sum  = agg_tensor.sum()

print(f"Min:  {tensor_min}")
print(f"Max:  {tensor_max}")
print(f"Mean: {tensor_mean}")
print(f"Sum:  {tensor_sum}")

Min:  0.0
Max:  100.0
Mean: 50.0
Sum:  5050.0


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [22]:
min_pos = agg_tensor.argmin()
max_pos = agg_tensor.argmax()

print(f"Index of Minimum: {min_pos.item()}")
print(f"Index of Maximum: {max_pos.item()}")

Index of Minimum: 0
Index of Maximum: 100


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [23]:
reshape_tensor = torch.arange(10)
# TODO: Reshape
reshaped = reshape_tensor.reshape(2, 5)

print(f"Original Shape: {reshape_tensor.shape}")
print(f"Reshaped Shape: {reshaped.shape}")

Original Shape: torch.Size([10])
Reshaped Shape: torch.Size([2, 5])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [24]:
tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)
# TODO: Stack vertically (dim=0)
vertical_stack = torch.cat((tensor1, tensor2), dim=0)

# TODO: Stack horizontally (dim=1)
horizontal_stack = torch.cat((tensor1, tensor2), dim=1)

print("Vertical:\n", vertical_stack)
print("\nHorizontal:\n", horizontal_stack)

Vertical:
 tensor([[0.8084, 0.5870],
        [0.9687, 0.8873],
        [0.9063, 0.2555],
        [0.2148, 0.1061]])

Horizontal:
 tensor([[0.8084, 0.5870, 0.9063, 0.2555],
        [0.9687, 0.8873, 0.2148, 0.1061]])


### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [25]:
squeeze_tensor = torch.rand(1, 3, 1)
# TODO: Squeeze
squeezed = tensor.squeeze()

# TODO: Unsqueeze on dim=0
unsqueezed = squeezed.unsqueeze(dim=0)

print(f"Original shape:   {tensor.shape}")
print(f"Squeezed shape:   {squeezed.shape}")
print(f"Unsqueezed shape: {unsqueezed.shape}")

Original shape:   torch.Size([3])
Squeezed shape:   torch.Size([3])
Unsqueezed shape: torch.Size([1, 3])


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [26]:
image_tensor = torch.rand(3, 100, 100)
# TODO: Permute
permuted = image_tensor.permute(1, 2, 0)

print(f"Original Shape: {image_tensor.shape}")
print(f"Permuted Shape: {permuted.shape}")

Original Shape: torch.Size([3, 100, 100])
Permuted Shape: torch.Size([100, 100, 3])


## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [27]:
index_tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
# TODO: Get 5
value_five = index_tensor[0, 1, 1]

# TODO: Get second row [4,5,6]
second_row = index_tensor[0, 1, :]

print(f"Value: {value_five.item()}")
print(f"Second Row: {second_row}")

Value: 5
Second Row: tensor([4, 5, 6])


## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [28]:
import numpy as np
numpy_array = np.array([1,2,3,4])
# TODO: Convert to tensor
from_numpy = torch.from_numpy(numpy_array)

print(f"NumPy Array: {numpy_array} (Type: {type(numpy_array)})")
print(f"Torch Tensor: {from_numpy} (Type: {type(from_numpy)})")

NumPy Array: [1 2 3 4] (Type: <class 'numpy.ndarray'>)
Torch Tensor: tensor([1, 2, 3, 4]) (Type: <class 'torch.Tensor'>)


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [29]:
pytorch_tensor = torch.tensor([5,6,7,8])
# TODO: Convert to NumPy
to_numpy = pytorch_tensor.numpy()

print(f"Torch Tensor: {pytorch_tensor} (Type: {type(pytorch_tensor)})")
print(f"NumPy Array: {to_numpy} (Type: {type(to_numpy)})")

Torch Tensor: tensor([5, 6, 7, 8]) (Type: <class 'torch.Tensor'>)
NumPy Array: [5 6 7 8] (Type: <class 'numpy.ndarray'>)


## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [32]:
# TODO: Set seed
torch.manual_seed(77)
rand1 = torch.rand(2,2)

# TODO: Reset seed for second tensor
rand2 = torch.rand(2,2)

# Check equality
are_equal = torch.equal(rand1, rand2)

print(f"Tensor A:\n{rand1}")
print(f"Tensor B:\n{rand2}")
print(f"Are they equal? {are_equal}")

Tensor A:
tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])
Tensor B:
tensor([[0.9503, 0.2564],
        [0.6645, 0.8609]])
Are they equal? False


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [34]:
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"

print(f"Using device: {device}")

x = torch.tensor([1, 2, 3], device=device)
print(f"Tensor is on: {x.device}")

Using device: cpu
Tensor is on: cpu


### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [35]:
gpu_tensor = torch.tensor([10, 20, 30])
# TODO: Move to device
gpu_tensor = gpu_tensor.to(device)

# TODO: Move back to CPU and to NumPy
cpu_numpy = gpu_tensor.cpu().numpy()

print(f"Tensor Device: {gpu_tensor.device}")
print(f"NumPy Result: {cpu_numpy}")

Tensor Device: cpu
NumPy Result: [10 20 30]
